version: 2

models:
  - name: infos_communes
    description: 'Fournit une table des communes avec les informations basiques'
    columns:
      - name: code_commune
        description: "Code commune. Clé primaire de la table"
        tests:
          - unique
          - not_null
        data_type: string
      - name: nom_commune
        description: "Nom de la commune"
        data_type: string
      - name: code_arrondissement
        description: "Code de l'arrondissement"
        data_type: string
      - name: code_departement
        description: "Code du département"
        data_type: string
      - name: code_region
        description: "Code de la région"
        data_type: string
      - name: population
        description: "Population de la commune"
        data_type: string
      - name: code_zone
        description: "Zone géographique (DROM, COM ou Métropole)"
        data_type: string
      - name: nom_arrondissement
        description: "Nom de l'arrondissement"
        data_type: string
      - name: nom_departement
        description: "Nom du département"
        data_type: string
      - name: nom_region
        description: "Nom de la région"
        data_type: string
      - name: commune_latitude
        description: "Latitude de la commune extraite des données de La Poste"
        data_type: float
      - name: commune_longitude
        description: "Longitude de la commune extraite des données de La Poste"
        data_type: float
      - name: commune_centre_geopoint
        description: "Point géographique central de la commune construit à partir des coordonnées de La Poste (geometry)"
        data_type: geometry
      - name: commune_contour
        description: "Contour géographique de la commune fourni par les shapefiles IGN (geometry)"
        data_type: geometry
      - name: SCoT
        description: "Nom du Schéma de Cohérence Territoriale (SCoT) auquel la commune est rattachée"
        data_type: string
      - name: "SIREN EPCI"
        description: "Code SIREN de l'Établissement Public de Coopération Intercommunale (EPCI) auquel la commune est rattachée"
        data_type: string

  - name: infos_postes
    description: 'Tables avec codes postaux uniques et leurs informations basiques.'
    columns:
      - name: code_postal
        description: "code postal. Primary key of the table"
        data_type: string
        tests:
            - unique
            - not_null
      - name: code_departement
        description: "code departement"
        data_type: string
      - name: nom_departement
        description: "nom departement"
        data_type: string
      - name: code_region
        description: "code region"
        data_type: string
      - name: nom_region
        description: "nom region"
        data_type: string
      - name: SCoT
        description: "nom de la SCoT"
        data_type: string
      - name: SIREN SCoT
        description: "N° SIREN de la SCoT"
        data_type: string


  - name: commune_centroid_poste
    description: 'Table de passage pour avoir une relation unique entre les codes postaux et les codes communes insee. Un code postal peut appartenir à plusieurs communes et une code commune insee peut appartenir plusieurs codes postaux.'

  - name: infos_departements
    description: 'Tables avec les informations géographiques et administratifs des départements.'
    columns:
      - name: code_departement
        description: "code département. Primary key of the table"
        data_type: string
        tests:
            - unique
            - not_null
      - name: nom_departement
        description: "nom departement"
        data_type: string
      - name: code_region
        description: "code region"
        data_type: string
      - name: nom_region
        description: "nom region"
        data_type: string
      - name: population_departement
        description: "population dans le département"
        data_type: string
      - name: contour_departement
        description: "contour géographique du département"
        data_type: geometry
        
