version: 2

sources:
  - name: sources
    schema: sources
    tables:
      - name: base_cc_emploi_pop_active_2016
      - name: base_cc_emploi_pop_active_2017
      - name: base_cc_emploi_pop_active_2018
      - name: base_cc_emploi_pop_active_2019
      - name: base_cc_emploi_pop_active_2020
      - name: base_cc_emploi_pop_active_2021
      - name: champs_disponibles_sources

  - name: prepare
    schema: prepare
    tables:
      - name: infos_communes

models:
  - name: Population_Active_communes_evolution
    description: "Évolution de la population active au niveau communal"
    columns:
      - name: CODGEO
        description: "Code géographique de la commune"
      - name: annee
        description: "Année de recensement"
