version: 2

sources:
  - name: sources
    schema: sources  # ou le schéma approprié où se trouvent vos tables sources
    tables:
      - name: champs_disponibles_sources
      # Ajoutez ici vos autres tables sources