version: 2

sources:
  - name: sources
    schema: sources
    tables:
      - name: base_cc_evol_struct_pop_2016
      - name: base_cc_evol_struct_pop_2017
      - name: base_cc_evol_struct_pop_2018
      - name: base_cc_evol_struct_pop_2019
      - name: base_cc_evol_struct_pop_2020
      - name: base_cc_evol_struct_pop_2021
      - name: champs_disponibles_sources

  - name: prepare
    schema: prepare
    tables:
      - name: infos_communes