version: 2

sources:
  - name: sources
    schema: sources  # ou le schéma approprié où se trouvent vos tables sources
    tables:
      - name: base_cc_carac_emploi_2016
      - name: base_cc_carac_emploi_2017
      - name: base_cc_carac_emploi_2018
      - name: base_cc_carac_emploi_2019
      - name: base_cc_carac_emploi_2020
      - name: base_cc_carac_emploi_2021
      - name: base_cc_coupl_fam_men_2016
      - name: base_cc_coupl_fam_men_2017
      - name: base_cc_coupl_fam_men_2018
      - name: base_cc_coupl_fam_men_2019
      - name: base_cc_coupl_fam_men_2020
      - name: base_cc_coupl_fam_men_2021
      - name: base_cc_diplomes_formation_2016
      - name: base_cc_diplomes_formation_2017
      - name: base_cc_diplomes_formation_2018
      - name: base_cc_diplomes_formation_2019
      - name: base_cc_diplomes_formation_2020
      - name: base_cc_diplomes_formation_2021
      - name: base_cc_emploi_pop_active_2016
      - name: base_cc_emploi_pop_active_2017
      - name: base_cc_emploi_pop_active_2018
      - name: base_cc_emploi_pop_active_2019
      - name: base_cc_emploi_pop_active_2020
      - name: base_cc_emploi_pop_active_2021
      - name: base_cc_evol_struct_pop_2016
      - name: base_cc_evol_struct_pop_2017
      - name: base_cc_evol_struct_pop_2018
      - name: base_cc_evol_struct_pop_2019
      - name: base_cc_evol_struct_pop_2020
      - name: base_cc_evol_struct_pop_2021
      - name: base_cc_logement_2016
      - name: base_cc_logement_2017
      - name: base_cc_logement_2018
      - name: base_cc_logement_2019
      - name: base_cc_logement_2020
      - name: base_cc_logement_2021
      - name: champs_disponibles_sources