version: 2

models:

- name: demographie_communes
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle de la commune.
  columns:

  - name:
    data_type:
    description:

- name: demographie_departements
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle du département.
  columns:

  - name:
    data_type:
    description:

- name: demographie_EPCI
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle de l'EPCI.
  columns:

  - name:
    data_type:
    description:

- name: demographie_SCoT
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle de la SCoT.
  columns:

  - name:
    data_type:
    description: