version: 2

models:

- name: demographie_communes_evolution
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle de la commune.


- name: demographie_departements_evolution
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle du département.


- name: demographie_EPCI_evolution
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle de l'EPCI.


- name: demographie_SCoT_evolution
  description: Rapporte les réponses sur la démographie du recensement agrégées à l'échelle de la SCoT.
