version: 2

models:
  - name: demographie_communes_evolution
    description: >
      Rapporte les réponses sur la démographie du recensement, agrégées à l'échelle de la commune.
      Les données proviennent des fichiers 'base_cc_evol_struct_pop_20XX' (2016 à 2021), retraitées
      pour obtenir un suivi temporel des variables démographiques.

sources:
  - name: sources
    tables:
      - name: base_cc_evol_struct_pop_2016
      - name: base_cc_evol_struct_pop_2017
      - name: base_cc_evol_struct_pop_2018
      - name: base_cc_evol_struct_pop_2019
      - name: base_cc_evol_struct_pop_2020
      - name: base_cc_evol_struct_pop_2021
