version: 2

models:

- name: activite_communes_evolution
  description: Rapporte les réponses sur l'activité du recensement agrégées à l'échelle de la commune.

- name: activite_departements
  description: Rapporte les réponses sur l'activité du recensement agrégées à l'échelle du département.


- name: activite_EPCI_evolution
  description: Rapporte les réponses sur l'activité du recensement agrégées à l'échelle de l'EPCI.


- name: activite_SCoT_evolution
  description: Rapporte les réponses sur l'activité du recensement agrégées à l'échelle de la SCoT.
