version: 2

models:

- name: mobilite_communes_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle de la commune.
  columns:

  - name:
    data_type:
    description:

- name: mobilite_departements_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle du département.
  columns:

  - name:
    data_type:
    description:

- name: mobilite_EPCI_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle de l'EPCI.
  columns:

  - name:
    data_type:
    description:

- name: mobilite_SCoT_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle de la SCoT.
  columns:

  - name:
    data_type:
    description: