version: 2

models:

- name: mobilite_communes_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle de la commune.


- name: mobilite_departements_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle du département.


- name: mobilite_EPCI_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle de l'EPCI.


- name: mobilite_SCoT_evolution
  description: Rapporte les réponses sur la mobilité du recensement agrégées à l'échelle de la SCoT.
