version: 2

sources:
  - name: sources
    schema: sources
    tables:
      - name: base_cc_evol_struct_pop_2016
      - name: base_cc_evol_struct_pop_2017
      - name: base_cc_evol_struct_pop_2018
      - name: base_cc_evol_struct_pop_2019
      - name: base_cc_evol_struct_pop_2020
      - name: base_cc_evol_struct_pop_2021
      - name: champs_disponibles_sources
      - name: base_cc_carac_emploi_2016
      - name: base_cc_carac_emploi_2017
      - name: base_cc_carac_emploi_2018
      - name: base_cc_carac_emploi_2019
      - name: base_cc_carac_emploi_2020
      - name: base_cc_carac_emploi_2021
      - name: base_cc_coupl_fam_men_2016
      - name: base_cc_coupl_fam_men_2017
      - name: base_cc_coupl_fam_men_2018
      - name: base_cc_coupl_fam_men_2019
      - name: base_cc_coupl_fam_men_2020
      - name: base_cc_coupl_fam_men_2021
      - name: base_cc_diplomes_formation_2016
      - name: base_cc_diplomes_formation_2017
      - name: base_cc_diplomes_formation_2018
      - name: base_cc_diplomes_formation_2019
      - name: base_cc_diplomes_formation_2020
      - name: base_cc_diplomes_formation_2021
      - name: base_cc_emploi_pop_active_2016
      - name: base_cc_emploi_pop_active_2017
      - name: base_cc_emploi_pop_active_2018
      - name: base_cc_emploi_pop_active_2019
      - name: base_cc_emploi_pop_active_2020
      - name: base_cc_emploi_pop_active_2021
      - name: base_cc_evol_struct_pop_2016
      - name: base_cc_evol_struct_pop_2017
      - name: base_cc_evol_struct_pop_2018
      - name: base_cc_evol_struct_pop_2019
      - name: base_cc_evol_struct_pop_2020
      - name: base_cc_evol_struct_pop_2021
      - name: base_cc_logement_2016
      - name: base_cc_logement_2017
      - name: base_cc_logement_2018
      - name: base_cc_logement_2019
      - name: base_cc_logement_2020
      - name: base_cc_logement_2021
      - name: cc_bdfdom_2017_dep
      - name: cc_bdfdom_2017_reg
      - name: cc_filosofi_2017_arr
      - name: cc_filosofi_2017_au2010
      - name: cc_filosofi_2017_com
      - name: cc_filosofi_2017_dep
      - name: cc_filosofi_2017_epci
      - name: cc_filosofi_2017_metro
      - name: cc_filosofi_2017_reg
      - name: cc_filosofi_2017_uu2010
      - name: cc_filosofi_2017_ze2010
      - name: cc_filosofi_2018_aav2020_geo2021
      - name: cc_filosofi_2018_arr_geo2021
      - name: cc_filosofi_2018_com_geo2021
      - name: cc_filosofi_2018_dep_geo2021
      - name: cc_filosofi_2018_epci_geo2021
      - name: cc_filosofi_2018_metro_geo2021
      - name: cc_filosofi_2018_reg_geo2021
      - name: cc_filosofi_2018_uu2020_geo2021
      - name: cc_filosofi_2018_ze2020_geo2021
      - name: cc_filosofi_2019_arr
      - name: cc_filosofi_2019_com
      - name: cc_filosofi_2019_ctcd
      - name: cc_filosofi_2019_dep
      - name: cc_filosofi_2019_epci
      - name: cc_filosofi_2019_ept
      - name: cc_filosofi_2019_metro
      - name: cc_filosofi_2019_reg
      - name: cc_filosofi_2019_uu2020
      - name: cc_filosofi_2019_ze2020
      - name: cc_filosofi_2020_aav2020
      - name: cc_filosofi_2020_arr
      - name: cc_filosofi_2020_bv2022
      - name: cc_filosofi_2020_com
      - name: cc_filosofi_2020_ctcd
      - name: cc_filosofi_2020_dep
      - name: cc_filosofi_2020_epci
      - name: cc_filosofi_2020_ept
      - name: cc_filosofi_2020_metro
      - name: cc_filosofi_2020_reg
      - name: cc_filosofi_2020_uu2020
      - name: cc_filosofi_2020_ze2020

  - name: prepare
    schema: prepare
    tables:
      - name: infos_communes

models:
  - name: Emplois_communes_evolution
  - name: Emplois_departements_evolution
  - name: Emplois_EPCI_evolution
  - name: Emplois_SCoT_evolution