version: 2

models:

- name: habitat_communes_evolution
  description: Rapporte les réponses sur les habitats du recensement agrégées à l'échelle de la commune.


- name: habitat_departements_evolution
  description: Rapporte les réponses sur les habitats du recensement agrégées à l'échelle du département.


- name: habitat_EPCI_evolution
  description: Rapporte les réponses sur les habitats du recensement agrégées à l'échelle de l'EPCI.


- name: habitat_SCoT_evolution
  description: Rapporte les réponses sur les habitats du recensement agrégées à l'échelle de la SCoT.
